EMPTY = -1
IDEN = 0
X = 1
Y = 2
Z = 3
S = 4
SDG = 5
T = 6
TDG = 7
H = 8
SWAP = 9
CTRL = 11 # "control" part of multi-qubit gate
TRACE = 12 # In the path between a gate part and a "control" or "swap" part
